brainstorm/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.conf.urls import url

app_name='brainstorm'

urlpatterns = [
    path('', views.GameListView.as_view(), name='smartgames'),
    path('rating', views.RatingView.as_view(), name = 'games_rating'),
    path('gamesarcive', views.ArchiveListView.as_view(), name = 'games_all'),
    path('playerteams', views.TeamDetailView.as_view(), name = 'personal_teams'),
    path('game/<int:pk>', views.GameDetailView.as_view(), name = 'game_detail'),
    path('joingame/<int:pk>', views.GameRegister.as_view(success_url=reverse_lazy('brainstorm:smartgames')), name='game_reg'),
    path('addroster/<int:pk>', views.AddRoster.as_view(success_url=reverse_lazy('brainstorm:smartgames')), name='add_roster'),
    path('addcontest/<int:pk>', views.AddContest.as_view(success_url=reverse_lazy('brainstorm:games_all')), name='add_contest'),
    path('gamequestions/<int:pk>', views.GameQuestions.as_view(), name='game_questions'),
    path('player/<int:pk>/confirm', views.PlayerConfirmView.as_view(success_url=reverse_lazy('brainstorm:smartgames')), name='player_confirm'),
    path('export/<int:pk>', views.export_users_xls, name='export_users_xls'),
]

smartgame/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('', include('brainstorm.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    path('accounts/', include('allauth.urls')),
    #path('accounts/', include('social_django.urls')),
    #url('accounts/', include('social_django.urls', namespace='social'))
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

brainstorm/models.py
from django.db import models
from django.core.validators import MinLengthValidator, RegexValidator, MinValueValidator
from django.utils.translation import gettext_lazy as _
from django.conf import settings


class Player(models.Model):
    """
    Игрок.
    """
    name = models.CharField(
        "ФИО",
        max_length=200,
        blank=True,
        validators=[MinLengthValidator(2,"Имя должно быть длиннее чем 1 символ")
        ]
    )
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{11}$', 
        message="Номер телефона должен быть введен в формате: '+99999999999'. "
    )
    phone = models.CharField(
        "Номер телефона",validators=[phone_regex], 
        max_length=12, 
        blank=True
    ) # validators should be a list
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        null = True, 
        on_delete = models.SET_NULL, 
        blank=True
    )

    class Meta:
        verbose_name = 'Игрок'
        verbose_name_plural = 'Игроки'

    def __str__(self):
        return self.name


class Team(models.Model):
    """
    Команда.
    """
    name = models.CharField(
        "Название команды",
        max_length=200,
        validators=[MinLengthValidator(2,"Название должно быть длиннее чем 1 символ")]
    )
    id_site = models.IntegerField(
        "Id для выгрузки на сайт ЧГК", 
        null = True, 
        blank=True, 
        validators=[MinValueValidator(0)]
    )

    class Meta:
        verbose_name = 'Команда'
        verbose_name_plural = 'Команды'

    def __str__(self):
        return self.name


class Game(models.Model):
    """
    Игра.
    """
    name = models.CharField(
        "Название игры",
        max_length=200,
        validators=[MinLengthValidator(2,"Название должно быть длиннее чем 1 символ")]
    )
    date_time = models.DateTimeField("дата и время", auto_now_add=False)
    location = models.CharField(
        "Место проведения",
        max_length=200,
        validators=[MinLengthValidator(2,"Место должно быть длиннее чем 1 символ")]  # TODO Сделать геодатой
    )

    class Meta:
        verbose_name = 'Игра'
        verbose_name_plural = 'Игры'

    def __str__(self):
        return f'{self.name} {self.date_time}'.format('%d.%m.%Y %H:%M')


class Roster(models.Model):
    """
    Состав команды, который участвовал в игре.
    """
    player = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL)
    team = models.ForeignKey(Team, null=True, on_delete=models.SET_NULL)
    game = models.ForeignKey(Game, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Состав команды'
        verbose_name_plural = 'Составы команд'

    def __str__(self):
        return f'{self.player} {self.team} {self.game}'


class Contest(models.Model):
    """
    Команда, зарегистрировавшаяся на игру.
    """
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Зарегистрировавшаяся команда'
        verbose_name_plural = 'Зарегистрировавшиеся команды'

    def __str__(self):
        return f'{self.team.name} {self.game.name}'


class Team_Player(models.Model):
    """
    Состав команды, один игрок может быть в нескольких командах.
    """
    class EarnedStatus(models.TextChoices) :
        CAPITAN = 'CP', _('Капитан')
        MAINPLAYER = 'MP', _('Игрок')
        EXPLAYER = 'EP', _('Неактивный')

    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    status =  models.CharField(
        "Статус игрока",
        max_length=2,
        choices=EarnedStatus.choices,
        default=EarnedStatus.MAINPLAYER,
    )

    class Meta:
        verbose_name = 'Команда игрока'
        verbose_name_plural = 'Команды игроков'

    def __str__(self):
        return f'{self.team.name} {self.player.name}'


class Question(models.Model):
    """
    Вопросы игры и кто ответил верно.
    """
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    q_number = models.IntegerField("Номер вопроса", validators=[MinValueValidator(0)])
    correct = models.BooleanField("Вопрос взят", null=True)

    class Meta:
        verbose_name = 'Вопрос игры'
        verbose_name_plural = 'Вопросы игры'

    def __str__(self):
        return f'{self.q_number} {self.contest.team.name} {self.contest.game.name}'


class Subtotal(models.Model):
    """
    Последний вопрос тура для промежуточных результатов.
    """
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    q_last = models.IntegerField("Финал тура", validators=[MinValueValidator(1)])

    class Meta:
        verbose_name = 'Финал тура'
        verbose_name_plural = 'Финалы туров'

    def __str__(self):
        return f'{self.game.name} {self.q_last}'

brainstorm/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from brainstorm.models import Game, Contest, Team_Player, Player, Question, Team, Roster, Subtotal
from brainstorm.forms import CreateFormContest, UpdateFormContest, CreateFormTeam, CreateFormRoster, CreateFormQuestions, CreateFormPlayer, CreateFormPlayerMin, UpdateFormStatus
from datetime import datetime
from django.db.models import Max, Min
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from dateutil.relativedelta import relativedelta
from django.db import connection, transaction
from openpyxl import Workbook
import xlwt
from django.http import HttpResponse


def xls_round(ws, row_num, start_num, finish_num):
    """
    Создает нужное количество колонок в excel с указанными номерами
    (файл, номер строки, первый номер, последний номер)
    """
    font_style = xlwt.XFStyle()
    columns = ['Team ID', 'Название', 'Город', 'Тур']
    res = [x for x in range(start_num, finish_num)]
    columns = columns+res
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)


def xls_results(ws, round, pk, start_num, finish_num, row_num):
    """
    Заполняет excel по указанным номерам.
    (файл, тур, первый номер вопроса, последний номер вопроса, номер строки)
    """
    font_style = xlwt.XFStyle()
    contests = Contest.objects.filter(game = pk)
    for tm in contests:
        team = Team.objects.get(id = tm.team.id) #получаем команду как объект, для отбора ниже
        row_num += 1
        ws.write(row_num, 0, team.id_site, font_style)
        ws.write(row_num, 1, team.name, font_style)
        ws.write(row_num, 2, 'Тюмень', font_style)
        ws.write(row_num, 3, round, font_style)
        # Выбираем вопросы текущей команды которые больше или равны первому номеру и меньше или равны последнему
        questions = Question.objects.filter(contest__team = team) \
                                    .filter(contest__game = pk) \
                                    .filter(q_number__lte = finish_num) \
                                    .filter(q_number__gte = start_num) \
                                    .order_by('q_number')
        for qs in questions:
            if qs.correct:
                # для подстраховки, что бы данные не поехали, номер колонки определяю по номеру вопроса.
                # в excel данные выводятся в три блока друг под другом.
                # поэтому из вопроса вычитаем, то количество вопросов на которое надо сдвинутся в обратную сторону
                # +4 колонки дополнительных данных
                # 1 - это верный ответ
                ws.write(row_num, qs.q_number-start_num+4, 1, font_style)

    return row_num


def export_users_xls(request, pk):
    """
    Выгрузка результатов игры в excel.
    (HttpRequest, id игры)
    """
    game = Game.objects.get(id = pk)
    response = HttpResponse(content_type='application/ms-excel') #возможно в итоге надо будет делать xmls но пока xls
    file_name = game.date_time.strftime("%d-%m-%Y")+".xls"
    response['Content-Disposition'] = 'attachment; filename="%s"' % file_name

    wb = xlwt.Workbook(encoding='utf-8')
    sheetname = game.name[:31] if len(game.name) > 31 else game.name
    sheetname = sheetname.replace(':','')
    ws = wb.add_sheet(sheetname)
    
    questions = Question.objects.filter(contest__game = pk).order_by('contest__team','q_number')
    max_q = questions.aggregate(Max('q_number')) #Сколько вопросов было на игре
    mq = max_q['q_number__max']
    #вопросов в турах поровну, делим их на три для трех блоков выгрузки.
    if mq>0:
        mq = int(mq/3)
    else:
        mq=0

    #Номера первого вопроса в блоке и последнего
    start_num=1
    finish_num = mq
    row_num = 1 #Первая строка
    # заполняем три блока выгрузки
    #TO DO переделать после того как добавлю туры.
    for i in range(1, 4):
        xls_round(ws, row_num, start_num, finish_num+1)
        row_num = xls_results(ws, str(i), pk, start_num, finish_num, row_num)
        start_num = start_num+mq
        finish_num = finish_num+mq
        row_num += 2

    wb.save(response) #сохраняем файл
    return response


class GameListView(ListView):
    """
    Главная страница.
    Список анонсированных игр, запросов на внесение составов. Распознавание новых пользователей.
    """
    model = Game
    template_name = "brainstorm/game_list.html"
    success_url = reverse_lazy('brainstorm:smartgames')

    def get(self, request):
        today = datetime.today()
        games = Game.objects.filter(date_time__gte = today).order_by('date_time') #Получаем еще непроведенные игры
        playername = ""
        if request.user.is_authenticated:
            try:
                currentplayer = Player.objects.get(user=self.request.user) #get чтобы получить единственный объект
            except Player.DoesNotExist:
                currentplayer = None
            # если пользователь не привязан к игроку, пробуем найти игрока без пользователя с его именем
            if currentplayer is None:
                username = request.user.last_name +" "+ request.user.first_name
                try:
                    results = Player.objects.filter(user__isnull=True).get(name__icontains=username)
                    playername = results.name
                    findplayer = True #если нашел игрока с такими же ФИО, но без привязанного пользователя
                except Player.DoesNotExist:
                    findplayer = False
            else:
                findplayer = False
            #CP - капитаны. Только они вносят составы.
            teams = Team_Player.objects.filter(player = currentplayer).filter(status = 'CP')
            valuelist = teams.values_list('team')
            twomonth = today - relativedelta(months=2)
            #выбираем игры в которых команда участвовала последние два месяца.
            contests = Contest.objects.filter(team__in = valuelist) \
                                    .filter(game__date_time__lte = today) \
                                    .filter(game__date_time__gte = twomonth)
            notinroster = [] #список игр по которым не внесен состав
            for earlygame in contests:
                #Проверяем внесен ли состав по игре
                if not Roster.objects.filter(team = earlygame.team).filter(game = earlygame.game).exists():
                   notinroster.append(earlygame.id)
            addroster = Contest.objects.filter(id__in = notinroster)
            ctx = {'games':games, 'addroster': addroster, 'findplayer':findplayer, 'playername':playername}
        else:
            #если не авторезирован, то он видит только список анонсированных игр
            ctx = {'games':games}
        retval = render(request, self.template_name, ctx)
        return retval

    def post(self, request):
        """
        Если нашел непривязанного игрока для этого пользователя, то мы попадает сюда.
        """
        username = request.user.last_name +" "+ request.user.first_name
        #Если подтвердил, что это он - записываем пользователя игроку.
        #Если отклонил - создаем нового игрока, что бы больше этого вопроса не возникало.
        if 'confirm' in request.POST:
            try:
                results = Player.objects.filter(user__isnull=True).get(name__icontains=username)
                results.user = request.user
                results.save()
            except Player.DoesNotExist:
                results = None
        elif 'decline' in request.POST:
            player = Player()
            player.user = request.user
            player.name = username
            player.save()
        return redirect(self.success_url)


class RatingView(DetailView):
    """
    Общий рейтинг по командам.
    """
    model = Contest
    template_name = "brainstorm/rating.html"

    def get(self, request):
        #Для рейтинга используем чистый sql запрос.
        result=_custom_sql()

        ctx = {'rating':result}
        retval = render(request, self.template_name, ctx)
        return retval


class ArchiveListView(ListView):
    """
    Общий список игр.
    """
    model = Game
    template_name = "brainstorm/game_archive.html"

    def get(self, request):
        games = Game.objects.all().order_by('-date_time')

        ctx = {'games':games}
        retval = render(request, self.template_name, ctx)
        return retval


class TeamDetailView(LoginRequiredMixin, DetailView):
    """
    Детализация по команде(командам) игрока.
    """
    model = Team_Player
    template_name = "brainstorm/team_detail.html"

    def get(self, request):
        try:
            currentplayer = Player.objects.get(user=self.request.user)
        except Player.DoesNotExist:
            currentplayer = None
        if request.user.is_superuser:
            playerteams = Team_Player.objects.all() # все команды для админа
            teams = Team.objects.order_by('name')
        else:
            # filter, а не get потому что команд может быть несколько
            playerteams = Team_Player.objects.filter(player = currentplayer).order_by('player__name')
            valuelist = playerteams.values_list('team')
            teams = Team.objects.filter(id__in = valuelist)
        teamplayers = Team_Player.objects.filter(team__in = teams).order_by('team__name', 'player__name')
        playerform=CreateFormPlayer(instance=Team_Player()) #добавление нового игрока
        #для нового игрока можно выбрать команду из доступных пользователю и любую команду если добавляет админ
        playerform.fields['team'].queryset = teams
        statusform = UpdateFormStatus(instance=Team_Player()) #изменение статусов игроков
        ctx = {'teams' : teamplayers, 'form_player': playerform, 'form_status': statusform}
        return render(request, self.template_name, ctx)

brainstorm/templates/brainstorm/add_contest.html
{% extends "baseform.html" %}
{% block content %}
<p>Кто участвовал в игре {{ currentgame.name }}?</p>
<form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <p>В списке нет нужной? Добавь новую команду.</p>
        {% csrf_token %}
        {{ form_team }}
        <div>
        <input type="submit" name="newteam" value="Создать!">
        </div>
    </div>
    {{ form_contest }}
    <div>
        <input type="submit" name = "contestteams" value="Сохранить">
        <input type="submit" value="Отмена" onclick="window.location.href='{% url 'brainstorm:smartgames' %}';return false;">
    </div>
</form>
{% endblock %}

brainstorm/templates/brainstorm/add_game.html
{% extends "baseform.html" %}
{% block content %}
{% load crispy_forms_tags %}

<form action="" method="post" id="upload_form" enctype="multipart/form-data">
{% csrf_token %}
{{ form_game|crispy }}
 <div>
        <input type="submit" name = "roster" value="Добавить">
        <input type="submit" value="Отмена" onclick="window.location.href='{% url 'brainstorm:smartgames' %}';return false;">
</div>
</form>
{% endblock %}

brainstorm/templates/brainstorm/add_roster.html
{% extends "baseform.html" %}
{% block content %}
<p>Кто был на игре {{ contest.game }}?</p>
<form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form_roster }}
    <div>
        <input type="submit" name = "roster" value="Они были!">
        <input type="submit" value="Отмена" onclick="window.location.href='{% url 'brainstorm:smartgames' %}';return false;">
    </div>
</form>
<button class="accordion">Добавить игрока:</button>
<div class="panel form-group">
    <p>
        <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form_player }}
        <input type="submit" name = "player" value="Добавить">
        </form>
    </p>
</div>


<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
      acc[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var panel = this.nextElementSibling;
        if (panel.style.maxHeight) {
          panel.style.maxHeight = null;
        } else {
          panel.style.maxHeight = panel.scrollHeight + "px";
        }
      });
    }
</script>
{% endblock %}

brainstorm/templates/brainstorm/game_archive.html
{% extends "baseform.html" %}
{% block content %}

<h2>Игры</h2>

{% if games %}
<ul class="list-group">
    {% for game in games %}
    <li class="list-group-item">
    <a href="{% url 'brainstorm:game_detail'  game.id %}" class="btn btn-light" style="text-align: left" role="button">{{ game.name }} {{ game.date_time|date:"d.m.Y" }}</a>
        {% if user.is_superuser %}
            <div>
            <a href="{% url 'brainstorm:game_questions' game.id %}" class="btn btn-light">Редактировать</a>
            <a href="{% url 'brainstorm:add_contest' game.id %}" class="btn btn-light">Внести участников</a>
            </div>
    </li>
</ul>
        {% endif %}
    {% endfor %}
{% endif %}

{% endblock %}

brainstorm/templates/brainstorm/game_detail.html
{% extends "baseform.html" %}
{% block content %}

<h2>{{ game.name }}</h2>

{% if questions %}
<a href="{% url 'brainstorm:export_users_xls' game.id %}">Выгрузить в excel</a>
<p>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover dataTables-example">
    <tr>
        <th>Команда</th>
        <th class="d-none d-sm-table-cell">1 тур</th>
        <th class="d-none d-sm-table-cell">2 тур</th>
        <th class="d-none d-sm-table-cell">3 тур</th>
        <th>Общий счет</th>
        <th>Спасено от гроба</th>
        <th>Рейтинг</th>
    </tr>
    {% for i in queryall  %}
    <tr>
        <td>{{ i.name }}</td>
        <td class="d-none d-sm-table-cell">{{ i.firstscore }}</td>
        <td class="d-none d-sm-table-cell">{{ i.secondscore }}</td>
        <td class="d-none d-sm-table-cell">{{ i.thirdscore }}</td>
        <td>{{ i.score }}</td>
        <td>{{ i.coffins_saved }}</td>
        <td>{{ i.rating }}</td>
    </tr>
    {% endfor %}
    </table>
</div>
</p>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover dataTables-example">
    <tr>
        <th>Команда</th>
        {% for i in listmax_q %}
            <th>{{ i }}</th>
        {% endfor %}
    </tr>
    {% for contest in contests %}
    <tr>
        <td>{{ contest.team }}</td>
        {% for question in contest.question_set.all|dictsort:"q_number" %}
            <td>
                {% if  question.correct %}
                <i class="fa fa-check" aria-hidden="true"></i>
                {% endif %}
            </td>
        {% endfor %}
    </tr>
    {% endfor %}
    </table>
</div>

{% endif %}

{% endblock %}

brainstorm/templates/brainstorm/game_list.html
{% extends "baseform.html" %}
{% block content %}
<!--<img class="logoimage" src= "/static/img/SmartGames.png" alt="интелектуальные игры">
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic">Title of a longer featured blog post</h1>
      <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
      <p class="lead mb-0"><a href="#" class="text-white fw-bold">Continue reading...</a></p>
    </div>
</div>>-->
<section class = "cta">
    <div class = "cta-content">
        <div class = "container px-5">
            <div class= "row gx-5 align-items-center text-white text-center">
                <!--<div class="mb-5 mb-lg-0 text-center text-lg-start">-->
                    <h1 class="display-1 lh-1 mb-3">SMART <span><img class="logoimage" style="width:100px;" src= "/static/img/HeandsSmall.png" alt="интелектуальные игры"> GAMES </span></h1>
                <!--</div>-->
            </div>
        </div>
    </div>
</section>


{% if games %}
<div class = "container py-4">
    {% for game in games %}
    <div class="h-15 p-5 bg-light border rounded-3 text-center">
        <h2>{{ game.name }}</h2>
        <p>{{ game.date_time }} {{ game.location }}</p>
        <a class ="buttonlike" href="{% url 'brainstorm:game_reg' game.id %}">Участвовать</a>
    </div>

    {% endfor %}
</div>
{% else %}
<div class = "container px-5">
    <div class = "align-item-center text-center"><h2>Скоро мы анонсируем новую игру!</h2></div>
</div>
{% endif %}
{% if addroster %}
<div class = "container py-4">
    {% for contest in addroster %}
    <div class="h-15 p-5 bg-light border rounded-3 text-center">
    <p class = "text-center">Ваша команда "{{ contest.team }}" участвовала в игре "{{ contest.game }}". Внесите ваш состав!</p>
    <a class ="buttonlike" href="{% url 'brainstorm:add_roster' contest.id %}">Заполнить</a>
    </div>
    {% endfor %}
</div>
{% endif %}

{% if findplayer %}
<div class="bs-example">
    <div id="myModal" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Это вы?</h5>
                </div>
                <div class="modal-body">
                    <p>Мы нашли в базе игрока по имени {{ playername }}. Это Вы?</p>
                </div>
                <div class="modal-footer">
                    <form action="" method="post" id="upload_form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="submit" name="confirm" class="btn btn-secondary" value="Да, это я">
                        <input type="submit" name="decline" class="btn btn-secondary" value="Нет">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}


<script>
    $(document).ready(function(){
        // Open modal on page load
        $("#myModal").modal('show');

         // Close modal on button click
        $(".btn").click(function(){
            $("#myModal").modal('hide');
        });
    });
</script>

{% endblock %}

brainstorm/templates/brainstorm/game_questions.html
{% extends "baseform.html" %}
{% block content %}


<form action="" method="post" id="upload_form" enctype="multipart/form-data">
{% if user.is_superuser %}
{% csrf_token %}
{{ form_questions }}
<input type="submit" name="thismany" value="ОК!">
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover dataTables-example" >
        <thead>
            <tr>
                <th>Команда</th>
                {% for i in listmax_q %} <!---for i in i|rjust:20 если нужно просто повторить n раз-->
                <th>{{ i }}</th> <!---forloop.counter -->
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for contest in contests %}
            <tr>
                <td class="editable" data-id="{{ contest.id }}" data-type="team">{{ contest.team }}</td>
                {% for question in contest.question_set.all|dictsort:"q_number" %}
                <td><input type="checkbox" name="{{ question.id }}"{% if  question.correct %} checked{% endif %}></td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>
<div>
    <input type="submit" name="results" value="Сохранить!">
</div>
{% endif %}
</form>
<!---не взлетело :( -->
<script>
    $(document).ready(function(){
        $(document).on("click",".editable",function(){
            var value=$(this).text();
            var input="<input type='text' class='input-data' value'"+value+"' class='form-control'>";
            $(this).html(input);
        })
    });
</script>
{% endblock %}

brainstorm/templates/brainstorm/team_detail.html
{% extends "baseform.html" %}
{% block content %}

{% if teams%}
<div class="row">
    {% for entry in teams %}
        {% ifchanged entry.team %}
        <div class="col-md-1 mb-1">
        </div>
        <div class="col-md-5 mb-1">
            <h4>{{ entry.team }}</h4>
        </div>
        <div class="col-md-6 mb-1">
        </div>
        {% endifchanged %}
        <div class="col-md-1 mb-1">
        </div>
        <div class="col-md-2 mb-1">
        <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        <span class="align-middle">{{ entry.player }}</span>
        </div>
        <div class="col-md-2 mb-1">
        <select name="{{ entry.player }}+{{ entry.team }}" onChange="this.form.submit();" class="form-select" data-title="Select Status" data-style="btn-default btn-block" data-menu-style="dropdown-blue">
        {% for val,name in form_status.fields.status.choices %}
            <option name="{{ entry.player }}" value="{{ val }}"{% if entry.status == val %} selected{% endif %}>{{ name }}</option>
            <!--<option>{{ entry.get_status_display }}</option>-->
        {% endfor %}
        </select>
        </form>
        </div>
        <div class="col-md-7 mb-1">
        </div>
    {% endfor %}
</div>
<button class="accordion">Добавить игрока:</button>
<div class="panel form-group">
  <p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form_player}}
  <input type="submit" name="newplayer" value="Сохранить">
  </form>
  </p>
</div>

{% else %}
<p>У тебя еще нет команды. Регистрируйся на игру!</p>
{% endif %}

<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
      acc[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var panel = this.nextElementSibling;
        if (panel.style.maxHeight) {
          panel.style.maxHeight = null;
        } else {
          panel.style.maxHeight = panel.scrollHeight + "px";
        }
      });
    }

</script>

<script>
   $( ".status" ).change(function() {
   alert( "Handler for .change() called." );
   $( "div" ).text( "fffffff" );

    });
</script>


{% endblock %}