brainstorm/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.conf.urls import url

app_name='brainstorm'

urlpatterns = [
    path('', views.GameListView.as_view(), name='smartgames'),
    path('rating', views.RatingView.as_view(), name = 'games_rating'),
    path('gamesarcive', views.ArchiveListView.as_view(), name = 'games_all'),
    path('playerteams', views.TeamDetailView.as_view(), name = 'personal_teams'),
    path('game/<int:pk>', views.GameDetailView.as_view(), name = 'game_detail'),
    path('joingame/<int:pk>', views.GameRegister.as_view(success_url=reverse_lazy('brainstorm:smartgames')), name='game_reg'),
    path('addroster/<int:pk>', views.AddRoster.as_view(success_url=reverse_lazy('brainstorm:smartgames')), name='add_roster'),
    path('addcontest/<int:pk>', views.AddContest.as_view(success_url=reverse_lazy('brainstorm:games_all')), name='add_contest'),
    path('gamequestions/<int:pk>', views.GameQuestions.as_view(), name='game_questions'),
    path('player/<int:pk>/confirm', views.PlayerConfirmView.as_view(success_url=reverse_lazy('brainstorm:smartgames')), name='player_confirm'),
    path('export/<int:pk>', views.export_users_xls, name='export_users_xls'),
]

smartgame/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('', include('brainstorm.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    path('accounts/', include('allauth.urls')),
    #path('accounts/', include('social_django.urls')),
    #url('accounts/', include('social_django.urls', namespace='social'))
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

brainstorm/forms.py
from django import forms
from django.forms import fields
from django.contrib.admin import widgets
from brainstorm.models import Team_Player, Team, Player, Game
from django.core.validators import MaxValueValidator, MinValueValidator

class CreateFormContest(forms.Form):
    """
    Выбор команды из списка при регистрации на игру.
    """
    team = forms.ModelChoiceField(
        label ='Команда',
        queryset=Team.objects.all(),
        to_field_name="name", blank = True,
        required = False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

class CreateFormTeam(forms.ModelForm):
    """
    Форма создания новой команды.
    """
    name = forms.CharField(
        label ='Название',
        required = False,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    class Meta:
        model = Team
        fields = ['name']


class CreateFormRoster(forms.Form):
    """
    Форма внесения состава игроков после игры.
    """
    playerlist = forms.ModelMultipleChoiceField(
        label ='Участники',
        queryset=Player.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

class CreateFormQuestions(forms.Form):
    howmany = forms.IntegerField(
        label = 'Сколько вопросов было?',
        required = False,
        validators=[MinValueValidator(1), MaxValueValidator(50)]
    )
    firstround = forms.IntegerField(
        label = 'Последний вопрос первого тура?',
        required = False,
        validators=[MinValueValidator(1), MaxValueValidator(50)]
    )
    secondround = forms.IntegerField(
        label = 'Последний вопрос второго тура?',
        required = False,
        validators=[MinValueValidator(1), MaxValueValidator(50)]
    )


class CreateFormPlayer(forms.ModelForm):
    """
    Форма добавления нового игрока с возможностью выбора из доступных команд.
    """
    team = forms.ModelChoiceField(
        label ='Команда',
        queryset=Team.objects.all(),
        required = True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Player
        fields = ['name','phone','team']
        help_texts = {
            'review ': ' ',
        }

        widgets = {
            'name' :  forms.TextInput(attrs={'class': 'form-control'}), #для визуально приятных форм
            'phone' : forms.TextInput(attrs={'class': 'form-control'}),
        }

class CreateFormPlayerMin(forms.ModelForm):
    """
    Форма добавление игрока без выбора команды. Для внесения состава.
    """
    class Meta:
        model = Player
        fields = ['name','phone']

        widgets = {
            'name' :  forms.TextInput(attrs={'class': 'form-control'}),
            'phone' : forms.TextInput(attrs={'class': 'form-control'}),
        }

class UpdateFormStatus(forms.ModelForm):
    """
    Изменине статуса игрока.
    """
    class Meta:
        model = Team_Player
        fields = ['status']


class UpdateFormContest(forms.ModelForm):
    """
    Изменине списка участвующих в игре команды.
    """
    team = forms.ModelMultipleChoiceField(
        label ='Участники',
        queryset=Team.objects.all().order_by('name'),
        widget=forms.CheckboxSelectMultiple,
        required = False
    )

    class Meta:
        model = Game
        fields = ['team']

brainstorm/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from brainstorm.models import Game, Contest, Team_Player, Player, Question, Team, Roster, Subtotal
from brainstorm.forms import CreateFormContest, UpdateFormContest, CreateFormTeam, CreateFormRoster, CreateFormQuestions, CreateFormPlayer, CreateFormPlayerMin, UpdateFormStatus
from datetime import datetime
from django.db.models import Max, Min
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from dateutil.relativedelta import relativedelta
from django.db import connection, transaction
from openpyxl import Workbook
import xlwt
from django.http import HttpResponse


def xls_round(ws, row_num, start_num, finish_num):
    """
    Создает нужное количество колонок в excel с указанными номерами
    (файл, номер строки, первый номер, последний номер)
    """
    font_style = xlwt.XFStyle()
    columns = ['Team ID', 'Название', 'Город', 'Тур']
    res = [x for x in range(start_num, finish_num)]
    columns = columns+res
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)


def xls_results(ws, round, pk, start_num, finish_num, row_num):
    """
    Заполняет excel по указанным номерам.
    (файл, тур, первый номер вопроса, последний номер вопроса, номер строки)
    """
    font_style = xlwt.XFStyle()
    contests = Contest.objects.filter(game = pk)
    for tm in contests:
        team = Team.objects.get(id = tm.team.id) #получаем команду как объект, для отбора ниже
        row_num += 1
        ws.write(row_num, 0, team.id_site, font_style)
        ws.write(row_num, 1, team.name, font_style)
        ws.write(row_num, 2, 'Тюмень', font_style)
        ws.write(row_num, 3, round, font_style)
        # Выбираем вопросы текущей команды которые больше или равны первому номеру и меньше или равны последнему
        questions = Question.objects.filter(contest__team = team) \
                                    .filter(contest__game = pk) \
                                    .filter(q_number__lte = finish_num) \
                                    .filter(q_number__gte = start_num) \
                                    .order_by('q_number')
        for qs in questions:
            if qs.correct:
                # для подстраховки, что бы данные не поехали, номер колонки определяю по номеру вопроса.
                # в excel данные выводятся в три блока друг под другом.
                # поэтому из вопроса вычитаем, то количество вопросов на которое надо сдвинутся в обратную сторону
                # +4 колонки дополнительных данных
                # 1 - это верный ответ
                ws.write(row_num, qs.q_number-start_num+4, 1, font_style)

    return row_num


def export_users_xls(request, pk):
    """
    Выгрузка результатов игры в excel.
    (HttpRequest, id игры)
    """
    game = Game.objects.get(id = pk)
    response = HttpResponse(content_type='application/ms-excel') #возможно в итоге надо будет делать xmls но пока xls
    file_name = game.date_time.strftime("%d-%m-%Y")+".xls"
    response['Content-Disposition'] = 'attachment; filename="%s"' % file_name

    wb = xlwt.Workbook(encoding='utf-8')
    sheetname = game.name[:31] if len(game.name) > 31 else game.name
    sheetname = sheetname.replace(':','')
    ws = wb.add_sheet(sheetname)
    
    questions = Question.objects.filter(contest__game = pk).order_by('contest__team','q_number')
    max_q = questions.aggregate(Max('q_number')) #Сколько вопросов было на игре
    mq = max_q['q_number__max']
    #вопросов в турах поровну, делим их на три для трех блоков выгрузки.
    if mq>0:
        mq = int(mq/3)
    else:
        mq=0

    #Номера первого вопроса в блоке и последнего
    start_num=1
    finish_num = mq
    row_num = 1 #Первая строка
    # заполняем три блока выгрузки
    #TO DO переделать после того как добавлю туры.
    for i in range(1, 4):
        xls_round(ws, row_num, start_num, finish_num+1)
        row_num = xls_results(ws, str(i), pk, start_num, finish_num, row_num)
        start_num = start_num+mq
        finish_num = finish_num+mq
        row_num += 2

    wb.save(response) #сохраняем файл
    return response


class GameListView(ListView):
    """
    Главная страница.
    Список анонсированных игр, запросов на внесение составов. Распознавание новых пользователей.
    """
    model = Game
    template_name = "brainstorm/game_list.html"
    success_url = reverse_lazy('brainstorm:smartgames')

    def get(self, request):
        today = datetime.today()
        games = Game.objects.filter(date_time__gte = today).order_by('date_time') #Получаем еще непроведенные игры
        playername = ""
        if request.user.is_authenticated:
            try:
                currentplayer = Player.objects.get(user=self.request.user) #get чтобы получить единственный объект
            except Player.DoesNotExist:
                currentplayer = None
            # если пользователь не привязан к игроку, пробуем найти игрока без пользователя с его именем
            if currentplayer is None:
                username = request.user.last_name +" "+ request.user.first_name
                try:
                    results = Player.objects.filter(user__isnull=True).get(name__icontains=username)
                    playername = results.name
                    findplayer = True #если нашел игрока с такими же ФИО, но без привязанного пользователя
                except Player.DoesNotExist:
                    findplayer = False
            else:
                findplayer = False
            #CP - капитаны. Только они вносят составы.
            teams = Team_Player.objects.filter(player = currentplayer).filter(status = 'CP')
            valuelist = teams.values_list('team')
            twomonth = today - relativedelta(months=2)
            #выбираем игры в которых команда участвовала последние два месяца.
            contests = Contest.objects.filter(team__in = valuelist) \
                                    .filter(game__date_time__lte = today) \
                                    .filter(game__date_time__gte = twomonth)
            notinroster = [] #список игр по которым не внесен состав
            for earlygame in contests:
                #Проверяем внесен ли состав по игре
                if not Roster.objects.filter(team = earlygame.team).filter(game = earlygame.game).exists():
                   notinroster.append(earlygame.id)
            addroster = Contest.objects.filter(id__in = notinroster)
            ctx = {'games':games, 'addroster': addroster, 'findplayer':findplayer, 'playername':playername}
        else:
            #если не авторезирован, то он видит только список анонсированных игр
            ctx = {'games':games}
        retval = render(request, self.template_name, ctx)
        return retval

    def post(self, request):
        """
        Если нашел непривязанного игрока для этого пользователя, то мы попадает сюда.
        """
        username = request.user.last_name +" "+ request.user.first_name
        #Если подтвердил, что это он - записываем пользователя игроку.
        #Если отклонил - создаем нового игрока, что бы больше этого вопроса не возникало.
        if 'confirm' in request.POST:
            try:
                results = Player.objects.filter(user__isnull=True).get(name__icontains=username)
                results.user = request.user
                results.save()
            except Player.DoesNotExist:
                results = None
        elif 'decline' in request.POST:
            player = Player()
            player.user = request.user
            player.name = username
            player.save()
        return redirect(self.success_url)


class RatingView(DetailView):
    """
    Общий рейтинг по командам.
    """
    model = Contest
    template_name = "brainstorm/rating.html"

    def get(self, request):
        #Для рейтинга используем чистый sql запрос.
        result=_custom_sql()

        ctx = {'rating':result}
        retval = render(request, self.template_name, ctx)
        return retval


class ArchiveListView(ListView):
    """
    Общий список игр.
    """
    model = Game
    template_name = "brainstorm/game_archive.html"

    def get(self, request):
        games = Game.objects.all().order_by('-date_time')

        ctx = {'games':games}
        retval = render(request, self.template_name, ctx)
        return retval


class TeamDetailView(LoginRequiredMixin, DetailView):
    """
    Детализация по команде(командам) игрока.
    """
    model = Team_Player
    template_name = "brainstorm/team_detail.html"

    def get(self, request):
        try:
            currentplayer = Player.objects.get(user=self.request.user)
        except Player.DoesNotExist:
            currentplayer = None
        if request.user.is_superuser:
            playerteams = Team_Player.objects.all() # все команды для админа
            teams = Team.objects.order_by('name')
        else:
            # filter, а не get потому что команд может быть несколько
            playerteams = Team_Player.objects.filter(player = currentplayer).order_by('player__name')
            valuelist = playerteams.values_list('team')
            teams = Team.objects.filter(id__in = valuelist)
        teamplayers = Team_Player.objects.filter(team__in = teams).order_by('team__name', 'player__name')
        playerform=CreateFormPlayer(instance=Team_Player()) #добавление нового игрока
        #для нового игрока можно выбрать команду из доступных пользователю и любую команду если добавляет админ
        playerform.fields['team'].queryset = teams
        statusform = UpdateFormStatus(instance=Team_Player()) #изменение статусов игроков
        ctx = {'teams' : teamplayers, 'form_player': playerform, 'form_status': statusform}
        return render(request, self.template_name, ctx)

brainstorm/templates/baseform.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static '/bootstrap/js/bootstrap.min.js' %}" >
    <link rel="stylesheet" href="{% static '/css/headmenu.css' %}" >
   <!---<link rel="stylesheet" href="/static/css/bodystyle.css" type="text/css"/> -->
   <!-- JavaScript Bundle with Popper -->
    <script src="{% static '/bootstrap/js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
    {% block navbar %}
    {% load app_tags %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'brainstorm:smartgames' %}">Smart games</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'brainstorm:games_rating' %}">Рейтинг</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'brainstorm:personal_teams' %}">Команды</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'brainstorm:games_all' %}">Игры</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Админка</a>
          </li>
          {% endif %}
          <!---<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>-->
        </ul>
        <ul class="navbar-nav navbar-right mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.get_username }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'brainstorm:smartgames' %}">Выйти</a></li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}?next={% url 'brainstorm:smartgames' %}">Войти</a>
          </li>
          {% endif %}
        </ul>
        <!--<form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>-->
      </div>
    </div>
  </nav>
  {% endblock %}
  {% include 'messages.html' %}
  {% block content %} {% endblock %}
</body>
</html>

brainstorm/templates/messages.html
{% if messages %}
  <div class="row">
  <div class="col-sm-6 col-sm-offset-3">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert" id="sc-alert">
        <p>{{ message }}</p>
      </div>
      {% endfor %}
    </div>

  </div>
{% endif %}

<script>
$("#sc-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#sc-alert").slideUp(500);
});
</script>